import React, { useEffect, useRef, useState, useCallback, memo } from "react";
import {
  MessageCircle,
  RotateCcw,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Share2,
  Heart,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Video } from "@/lib/api/client";
import { videoApi } from "@/lib/api/client";

interface VideoPlayerProps {
  video: Video;
  isActive: boolean;
  shouldLoad?: boolean;
  onActivate?: () => void;
}

const VideoPlayer = memo(
  ({ video, isActive, shouldLoad = true, onActivate }: VideoPlayerProps) => {
    const videoRef = useRef<HTMLVideoElement>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<Error | null>(null);
    const [isEnded, setIsEnded] = useState(false);
    const [isPlaying, setIsPlaying] = useState(false);
    const [isMuted, setIsMuted] = useState(true);
    const [showControls, setShowControls] = useState(false);
    const [likeCount, setLikeCount] = useState(video.likes);
    const [shareCount, setShareCount] = useState(video.shares);
    const [isLiked, setIsLiked] = useState(false);
    const [isSharing, setIsSharing] = useState(false);
    const [showShareToast, setShowShareToast] = useState(false);
    const [showHeartAnimation, setShowHeartAnimation] = useState(false);
    const controlsTimeoutRef = useRef<NodeJS.Timeout | null>(null);
    const lastTapRef = useRef<number>(0);
    const previousVideoIdRef = useRef<string>(video.id);

    useEffect(() => {
      if (previousVideoIdRef.current !== video.id) {
        previousVideoIdRef.current = video.id;
        setLikeCount(video.likes);
        setShareCount(video.shares);
        setIsLiked(false);
        setShowControls(false);
        setIsEnded(false);
      }
    }, [video.id, video.likes, video.shares]);

    useEffect(() => {
      const vid = videoRef.current;
      if (!vid) return;

      if (isActive) {
        setIsEnded(false);
        vid.play().catch((err) => {
          console.warn("Autoplay prevented:", err);
        });
      } else {
        vid.pause();
        setIsPlaying(false);
        setShowControls(false);
      }
    }, [isActive]);

    // GENERATED BY AI (DEEPSEEK)
    useEffect(() => {
      const vid = videoRef.current;
      if (!vid) return;

      const handleEnded = () => {
        setIsEnded(true);
        setIsPlaying(false);
        setShowControls(true);
      };
      const handleWaiting = () => setIsLoading(true);
      const handlePlaying = () => {
        setIsLoading(false);
        setIsPlaying(true);
        hideControlsAfterDelay();
      };
      const handleCanPlay = () => setIsLoading(false);
      const handleError = () => {
        setError(new Error("Video failed to load"));
        setIsLoading(false);
        setIsPlaying(false);
      };
      const handleLoadStart = () => setIsLoading(true);
      const handlePause = () => {
        setIsPlaying(false);
        setShowControls(true);
      };

      vid.addEventListener("ended", handleEnded);
      vid.addEventListener("waiting", handleWaiting);
      vid.addEventListener("playing", handlePlaying);
      vid.addEventListener("canplay", handleCanPlay);
      vid.addEventListener("error", handleError);
      vid.addEventListener("loadstart", handleLoadStart);
      vid.addEventListener("pause", handlePause);

      return () => {
        vid.removeEventListener("ended", handleEnded);
        vid.removeEventListener("waiting", handleWaiting);
        vid.removeEventListener("playing", handlePlaying);
        vid.removeEventListener("canplay", handleCanPlay);
        vid.removeEventListener("error", handleError);
        vid.removeEventListener("loadstart", handleLoadStart);
        vid.removeEventListener("pause", handlePause);
        if (controlsTimeoutRef.current) {
          clearTimeout(controlsTimeoutRef.current);
        }
      };
    }, []);

    const hideControlsAfterDelay = useCallback(() => {
      if (controlsTimeoutRef.current) {
        clearTimeout(controlsTimeoutRef.current);
      }
      controlsTimeoutRef.current = setTimeout(() => {
        if (isPlaying) {
          setShowControls(false);
        }
      }, 2000);
    }, [isPlaying]);

    const handleLike = useCallback(async () => {
      const newLikedState = !isLiked;
      const newLikeCount = newLikedState ? likeCount + 1 : likeCount - 1;

      setIsLiked(newLikedState);
      setLikeCount(newLikeCount);

      if (newLikedState) {
        setShowHeartAnimation(true);
        setTimeout(() => setShowHeartAnimation(false), 1000);
      }

      try {
        await videoApi.update(video.id, { likes: newLikeCount });
      } catch (error) {
        setIsLiked(!newLikedState);
        setLikeCount(likeCount);
        console.error("Failed to update like:", error);
      }
    }, [isLiked, likeCount, video.id]);

    const handleVideoClick = useCallback(
      (e: React.MouseEvent) => {
        e.stopPropagation();

        const now = Date.now();
        if (now - lastTapRef.current < 300) {
          if (!isLiked) {
            handleLike();
          }
          lastTapRef.current = 0;
          return;
        }
        lastTapRef.current = now;

        if (!isActive) {
          onActivate?.();
          return;
        }

        const vid = videoRef.current;
        if (!vid) return;

        if (vid.paused) {
          vid.play().catch(() => {});
          setIsPlaying(true);
          hideControlsAfterDelay();
        } else {
          vid.pause();
          setIsPlaying(false);
          setShowControls(true);
          if (controlsTimeoutRef.current) {
            clearTimeout(controlsTimeoutRef.current);
          }
        }
      },
      [isActive, onActivate, isLiked, handleLike, hideControlsAfterDelay],
    );

    const handlePlayPauseClick = useCallback(
      (e: React.MouseEvent) => {
        e.stopPropagation();
        const vid = videoRef.current;
        if (!vid) return;

        if (vid.paused) {
          vid.play().catch(() => {});
          setIsPlaying(true);
          hideControlsAfterDelay();
        } else {
          vid.pause();
          setIsPlaying(false);
          if (controlsTimeoutRef.current) {
            clearTimeout(controlsTimeoutRef.current);
          }
        }
      },
      [hideControlsAfterDelay],
    );

    const handleMuteClick = useCallback(
      (e: React.MouseEvent) => {
        e.stopPropagation();
        const vid = videoRef.current;
        if (vid) {
          vid.muted = !vid.muted;
          setIsMuted(!isMuted);
        }
        setShowControls(true);
        hideControlsAfterDelay();
      },
      [isMuted, hideControlsAfterDelay],
    );

    const handleShareClick = useCallback(
      async (e: React.MouseEvent) => {
        e.stopPropagation();
        if (isSharing) return;
        setIsSharing(true);

        const shareUrl = `${window.location.origin}/video/${video.id}`;
        try {
          if (navigator.share) {
            await navigator.share({
              title: video.customerName,
              text: `Check out ${video.customerName}'s video!`,
              url: shareUrl,
            });
          } else {
            await navigator.clipboard.writeText(shareUrl);
            setShowShareToast(true);
            setTimeout(() => setShowShareToast(false), 2000);
          }

          const newShareCount = shareCount + 1;
          setShareCount(newShareCount);
          await videoApi.update(video.id, { shares: newShareCount });
        } catch (error) {
          if ((error as Error).name !== "AbortError") {
            console.error("Share failed:", error);
          }
        } finally {
          setIsSharing(false);
        }
      },
      [isSharing, shareCount, video],
    );

    const handleRetry = useCallback(
      (e: React.MouseEvent) => {
        e.stopPropagation();
        const vid = videoRef.current;
        if (!vid) return;
        setError(null);
        setIsLoading(true);
        vid.load();
        if (isActive) {
          vid.play().catch(() => {});
        }
      },
      [isActive],
    );

    const handleReplay = useCallback((e: React.MouseEvent) => {
      e.stopPropagation();
      const vid = videoRef.current;
      if (!vid) return;
      setIsEnded(false);
      vid.currentTime = 0;
      vid.play().catch(() => {});
      setShowControls(false);
    }, []);

    const formatCount = (count: number): string => {
      if (count >= 1000000) return (count / 1000000).toFixed(1) + "M";
      if (count >= 1000) return (count / 1000).toFixed(1) + "K";
      return count.toString();
    };

    return (
      <div
        className="relative h-full w-full bg-black flex items-center justify-center overflow-hidden rounded-lg"
        onClick={handleVideoClick}
        data-testid={`player-${video.id}`}
      >
        <video
          ref={videoRef}
          src={shouldLoad ? video.videoUrl : undefined}
          poster={video.thumbnail}
          muted={isMuted}
          playsInline
          controls={false}
          disablePictureInPicture
          controlsList="nofullscreen nodownload noremoteplayback"
          preload={shouldLoad ? "metadata" : "none"}
          className="h-full w-full object-cover"
          loop={false}
        />

        <AnimatePresence>
          {showHeartAnimation && (
            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              animate={{ opacity: [0, 1, 1, 0], scale: [0, 1.2, 1, 0.8] }}
              exit={{ opacity: 0, scale: 0 }}
              transition={{
                duration: 1,
                times: [0, 0.2, 0.4, 1],
                ease: "easeOut",
              }}
              className="absolute inset-0 z-50 flex items-center justify-center pointer-events-none"
            >
              <Heart
                className="h-24 w-24 text-white drop-shadow-lg"
                fill="white"
                stroke="white"
                strokeWidth={1}
              />
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence>
          {showShareToast && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 50 }}
              className="absolute bottom-32 left-1/2 transform -translate-x-1/2 z-50 bg-black/80 text-white px-4 py-2 rounded-full text-sm backdrop-blur-md"
            >
              Link copied to clipboard!
            </motion.div>
          )}
        </AnimatePresence>

        {error && (
          <div className="absolute inset-0 z-30 flex flex-col items-center justify-center bg-black/80 text-white">
            <p className="mb-4 text-sm">Video failed to load</p>
            <button
              onClick={handleRetry}
              className="flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-sm hover:bg-white/30"
            >
              <RotateCcw className="h-4 w-4" /> Retry
            </button>
          </div>
        )}

        <AnimatePresence>
          {isLoading && isActive && !error && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-10 flex items-center justify-center"
            >
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-white/30 border-t-white" />
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence>
          {isEnded && isActive && !error && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-20 flex items-center justify-center bg-black/40 cursor-pointer"
              onClick={handleReplay}
            >
              <div className="flex flex-col items-center gap-2 text-white">
                <RotateCcw className="h-10 w-10" />
                <span className="text-sm font-medium">Replay</span>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence>
          {showControls && isActive && !error && !isEnded && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-30 flex flex-col items-center justify-center gap-4"
            >
              <button
                onClick={handleMuteClick}
                className="flex h-12 w-12 items-center justify-center rounded-full bg-black/50 backdrop-blur-sm hover:scale-110 active:scale-95 transition-transform"
              >
                {isMuted ? (
                  <VolumeX className="h-6 w-6 text-white" />
                ) : (
                  <Volume2 className="h-6 w-6 text-white" />
                )}
              </button>
              <button
                onClick={handlePlayPauseClick}
                className="flex h-16 w-16 items-center justify-center rounded-full bg-black/50 backdrop-blur-sm hover:scale-110 active:scale-95 transition-transform"
              >
                {isPlaying ? (
                  <Pause className="h-8 w-8 text-white" fill="white" />
                ) : (
                  <Play className="h-8 w-8 text-white ml-1" fill="white" />
                )}
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {isActive && !error && (
          <>
            <div
              className="absolute right-3 bottom-24 z-40 flex flex-col items-center gap-5"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex flex-col items-center">
                <button
                  onClick={handleLike}
                  className="flex h-12 w-12 items-center justify-center rounded-full active:scale-90 transition-transform"
                >
                  <Heart
                    className={`h-7 w-7 ${isLiked ? "text-red-500 fill-red-500" : "text-white"}`}
                    strokeWidth={2}
                  />
                </button>
                <span className="text-xs font-semibold text-white mt-0.5">
                  {formatCount(video.likes)}
                </span>
              </div>
              <div className="flex flex-col items-center">
                <button className="flex h-12 w-12 items-center justify-center rounded-full active:scale-90 transition-transform">
                  <MessageCircle
                    className="h-7 w-7 text-white"
                    strokeWidth={2}
                  />
                </button>
                <span className="text-xs font-semibold text-white mt-0.5">
                  {formatCount(video.comments)}
                </span>
              </div>
              <div className="flex flex-col items-center">
                <button
                  onClick={handleShareClick}
                  disabled={isSharing}
                  className="flex h-12 w-12 items-center justify-center rounded-full active:scale-90 transition-transform"
                >
                  <Share2 className="h-6 w-6 text-white" strokeWidth={2} />
                </button>
                <span className="text-xs font-semibold text-white mt-0.5">
                  {formatCount(shareCount)}
                </span>
              </div>
            </div>
          </>
        )}
      </div>
    );
  },
);

VideoPlayer.displayName = "VideoPlayer";
export default VideoPlayer;
